# Generated by Django 2.1 on 2019-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0013_auto_20160705_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestperson', models.TextField(max_length=255, null=True)),
            ],
        ),
    ]
